server.port=8443

spring.datasource.url=jdbc:postgresql://localhost:5432/antivirus
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.ssl.enabled=true
server.ssl.key-store=classpath:antivirus.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:antivirus23399}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=srv23399-antivirus

security.jwt.access-ttl-seconds=900
security.jwt.refresh-ttl-seconds=2592000
security.jwt.secret=${JWT_SECRET:THIS_IS_A_SUPER_LONG_SECRET_KEY_32+_CHARS_MINIMUM_2026}
